#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hvz.Resource", IsApplication=true)]

namespace Hvz
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_default_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_size = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int contentLayout = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int contentView = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int humanCard = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int humanCount = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int humansText = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int space1 = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int zombieCount = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int zombiesText = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
